---
# tasks file for mantenimiento

- name: Copiar scripts de mantenimiento al servidor
  copy:
    src: "{{ item }}"
    dest: "{{ mantenimiento_dir }}/"
    owner: root
    group: root
    mode: '0755'
  loop:
    - restart_nginx.sh
    - backup_infra-cloud.sh
    - restaurar_backup_infra-cloud.sh
  become: yes

- name: Programar tarea automática diaria (backup + reinicio)
  cron:
    name: "Ejecución diaria de mantenimiento"
    minute: "0"
    hour: "3"
    user: root
    job: "{{ mantenimiento_dir }}/backup_infra-cloud.sh && {{ mantenimiento_dir }}/restart_nginx.sh"
  become: yes
