---
# tasks file for nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags: nginx

- name: Ensure Nginx service is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx

- name: Create web site directory
  file:
    path: "{{ site_root }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0755'
  tags: nginx

- name: Copy static website files (index.html and style.css)
  copy:
    src: "{{ item }}"
    dest: "{{ site_root }}/"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  with_items:
    - files/index.html
    - files/style.css
  tags: nginx

- name: Configure Nginx site from template
  template:
    src: "{{ template_src }}"
    dest: "{{ nginx_config_path }}/{{ site_name }}"
    owner: root
    group: "{{ nginx_group }}"
    mode: '0640'
  tags: nginx

- name: Create symbolic link in sites-enabled
  file:
    src: "{{ nginx_config_path }}/{{ site_name }}"
    dest: "{{ nginx_enabled_path }}/{{ site_name }}"
    state: link
  tags: nginx

- name: Disable Nginx default sites
  file:
    path: "{{ nginx_enabled_path }}/{{ item }}"
    state: absent
  loop: "{{ default_sites }}"
  tags: nginx

- name: Restart Nginx to apply changes
  service:
    name: nginx
    state: restarted
  tags: nginx

