---
# vars file for common

server_hostname: "server01"
timezone: "Europe/Madrid"
basic_tools:
  - curl
  - wget
  - vim
  - nano
  - htop
  - tree
  - net-tools
  - iputils-ping
ufw_allowed_ports:
  - 22
  - 80
  - 443
